### ISSUE TITLE
Grader Evaluation Triggers Too Early

### ISSUE THREAD

**Issue by Zongshun96** [dmpalyvos/debs-2020-challenge#3]
Hi,
It looks like in resource.benchmark, the getscore() method is call when receiving the GET request after replying {'records': ''}, 200 to the last GET request. Or in other words, it is triggered when the sender is requesting more data than the benchmark has.

This causes an issue that if we have the GET request function and POST request function run in 2 separate threads, then we have to coordinate between the 2 threads to let the GET thread wait for POST thread to finish.
 So, can we change the logic a little bit that let a POST request can trigger the evaluation instead of a GET? Say a POST request sends an empty string, "", and then the grader knows the input stream has finished and starts an evaluation?

We would be grateful as it would benefit us. While to me it makes more sense that only when the last part of solution is POST'ed to grader, the grader knows the input stream finished. Instead of when the grader has sent all the data, and then it thinks the input stream finished.

Thanks,
Zongshun Zhang

**Comment by Zongshun96** [comment]
https://github.com/dmpalyvos/debs-2020-challenge/blob/51457091a2e792293c264265f126b6a0979b3062/grader_app/resources.py#L35-L38


I am assuming the links above in GET handler in grader would trigger the evaluation. Please correct me if I am wrong.

Thanks,
Zongshun Zhang

**Comment by dmpalyvos** [comment]
Hi,

Unfortunately this is a change that will break the backwards compatibility with already submitted solutions. However, I am trying to think if your problem could be solved in another way. If I understand your architecture correctly, then wouldn’t it be possible to achieve your goal by doing the following?

1. GET all the data with the GET thread until you receive the empty batch.
1. POST all your answers with the POST thread.
1. *Instead of sending an empty POST to signal that you finished, do a final dummy GET request from the POST thread to trigger the grading.*

Let me know if this makes sense!

Kind Regards,
Dimitris

**Comment by Zongshun96** [comment]
Hi,
   Yes, that helps. Thanks!

Best,
Zongshun Zhang
